version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vest-cctv-api"
s3_bucket = "vest-cctv"
s3_prefix = "vest-cctv-api"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
