AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: vestcctv-api
  
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
    Architectures: 
      - x86_64

Resources:
  BingReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.bingreports
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts

  TweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.tweets
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.weather
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts