AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: vestcctv-api

Parameters:
  BingMapsAPIKey:
    Type: String
    Description: "Bing maps API Key"
  TwitterAPIToken:
    Type: String
    Description: "Twitter API Token"
  OpenWeatherAPIKey:
    Type: String
    Description: "Open Weather API Key"

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
    Architectures: 
      - x86_64

Resources:
  VestCCTVApi:
    Type: AWS::Serverless::HttpApi
    StageName: $default
    CorsConfiguration:
      AllowOrigins: 
        - "https://vestcctv.lokoydesign.com"

  BingReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.bingreports
      Environment:
        Variables:
          BING_MAPS_API_KEY: !Ref BingMapsAPIKey
      Events:
        BingReports:
          Type: HttpApi
          Properties:
            ApiId: VestCCTVApi
            Method: get
            Path: /bingreports
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts

  TweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.tweets
      Environment:
        Variables:
          TWITTER_API_TOKEN: !Ref TwitterAPIToken
      Events:
        BingReports:
          Type: HttpApi
          Properties:
            ApiId: VestCCTVApi
            Method: get
            Path: /tweets
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoints/
      Handler: index.weather
      Environment:
        Variables:
          OPEN_WEATHER_API_KEY: !Ref OpenWeatherAPIKey
      Events:
        BingReports:
          Type: HttpApi
          Properties:
            ApiId: VestCCTVApi
            Method: get
            Path: /weather
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints: 
          - index.ts